apiVersion: v1
kind: Pod
metadata:
  name: ci-pod
  labels:
    env: devops
  namespace: ns-manifest 
spec:
  containers:
  - name: nginx-cipod
    image: nginx
    ports:
    - name: ci-port
      containerPort: 80
