apiVersion: v1
kind: Service
metadata:
  name: ci-svc
  labels:
    env: devops 
  namespace: ns-manifest
spec:
  type: ClusterIP
  selector:
    env: devops 
  ports:
  - name: ci-svc-port 
    protocol: TCP
    port: 80
    targetPort: 80
