apiVersion: v1 
kind: Pod 
metadata: 
  name: selector-pod
  labels:
    type: selector
spec:
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "taint"
    effect: "NoSchedule"
  nodeSelector:
    type: prod 
  containers:
  - name: inginx-cont
    image: nginx:latest 
    ports: 
    - containerPort: 80 