apiVersion: v1
kind: Service 
metadata:
  name: np-svc
  labels:
    env: np-pod
  namespace: ns-manifest 
spec:
  type: NodePort
  selector: 
    env: np-pod 
  ports:
  - name: np-svc-port
    protocol: TCP
    port: 80 
    targetPort: 80

