apiVersion: v1
kind: ReplicationController 
metadata:
  name: rc-pod
  labels:
    env: rc-label
spec:
  replicas: 2
  selector:
    env: rc-label
  template: 
    metadata:
      name: nginx-template
      labels:
        env: rc-label
    spec:
      containers:
      - name: rc-cont
        image: nginx 
        ports:
        - containerPort: 80
...
---
apiVersion: v1
kind: Service 
metadata:
  name: rc-svc
  labels:
    env: rc-label
spec:
  type: NodePort
  selector: 
    env: rc-label
  ports:
  - name: rc-svc-port
    protocol: TCP
    port: 80
    targetPort: 80