apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: mypv
  labels:
    vol: pv 
spec: 
  capacity:
    storage: 10Gi
  accessModes:    
  - ReadWriteOnce
  volumeMode: Filesystem 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: standard 
  hostPath:
    path: /mnt/data
