apiVersion: autoscaling/v2
kind: 0HorizontalPodAutoscaler
metadata: 
  name: hpa 
  labels:
    type: autoscale 
  namespace: autoscaling 
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: hpa-deploy 
  minReplicas: 1
  maxReplicas: 5
  metrics: 
  - type: Resource 
    resource: 
      name: cpu
      target: 
        type: Utilization 
        averageUtilization: 50 